/* =============================================================================
 *  kernel/tls_client.c — BearSSL-backed HTTPS client (FalconOS 1.3 TLS)
 * -----------------------------------------------------------------------------
 *  This translation unit is the bridge between FalconOS's bare-metal kernel
 *  and the vendored BearSSL TLS 1.2 implementation (vendor/bearssl/).  It
 *  intentionally pulls in real BearSSL symbols so the static archive
 *  build/libbearssl.a is force-linked into the kernel ELF and we know,
 *  byte-for-byte at link time, that the TLS code path is shippable.
 *
 *  Status (v1.3-tls foundation commit):
 *    * BearSSL client engine is allocated and initialised in tls_init().
 *    * The X.509 minimal validator is wired up with embedded Mozilla
 *      roots (kernel/tls_roots.c, generated from Mozilla NSS bundle).
 *    * HMAC_DRBG is seeded from the PIT tick + RTC second + RDRAND.
 *    * Transport (TCP) is the missing piece — bareTCP lives next door
 *      and currently returns "would-block" so tls_https_get() returns
 *      TLS_ERR_UNCONFIGURED until ARP/IP/TCP/DHCP/DNS land.
 *
 *  Once bareTCP is alive, the loop in tls_https_get() below is already
 *  shaped correctly for BearSSL's record-engine state machine.
 * ============================================================================= */

#include "falcon.h"
#include "../vendor/bearssl/inc/bearssl.h"

/* ----------------------------------------------------------------------------
 * 1. RNG seeding — HMAC_DRBG over (PIT ticks, RTC second, optional RDRAND).
 *    BearSSL's hmac_drbg requires a ≥ 128-bit seed.  We collect 32 bytes
 *    by mixing four independent sources at boot.
 * ---------------------------------------------------------------------------- */
static br_hmac_drbg_context g_drbg;
static bool                 g_drbg_ready = false;

static u64 tls_rdtsc(void)
{
    u32 lo, hi;
    __asm__ volatile ("rdtsc" : "=a"(lo), "=d"(hi));
    return ((u64)hi << 32) | lo;
}

static bool cpu_has_rdrand(void)
{
    u32 ecx;
    __asm__ volatile ("cpuid"
                      : "=c"(ecx)
                      : "a"(1)
                      : "ebx", "edx");
    return (ecx & (1u << 30)) != 0;
}

static u64 rdrand_or_zero(void)
{
    if (!cpu_has_rdrand()) return 0;
    u64 v = 0;
    unsigned char ok = 0;
    /* 10 retries per the Intel spec for transient failure. */
    for (i32 i = 0; i < 10 && !ok; i++)
        __asm__ volatile ("rdrand %0; setc %1" : "=r"(v), "=qm"(ok));
    return ok ? v : 0;
}

static void tls_seed_drbg(void)
{
    u8 seed[32];
    u64 a = tls_rdtsc();
    u64 b = rdrand_or_zero();
    u32 c = pit_ms();
    rtc_time_t rt; rtc_now(&rt);
    u32 d = (u32)((rt.hour * 3600u) + (rt.min * 60u) + rt.sec);
    /* Mix: 8 bytes TSC, 8 bytes RDRAND, 4 ticks, 4 seconds, 8 bytes derived. */
    for (i32 i = 0; i < 8; i++) seed[i]      = (u8)(a >> (i * 8));
    for (i32 i = 0; i < 8; i++) seed[8 + i]  = (u8)(b >> (i * 8));
    for (i32 i = 0; i < 4; i++) seed[16 + i] = (u8)(c >> (i * 8));
    for (i32 i = 0; i < 4; i++) seed[20 + i] = (u8)(d >> (i * 8));
    u64 mix = a ^ b ^ ((u64)c << 32) ^ d;
    for (i32 i = 0; i < 8; i++) seed[24 + i] = (u8)(mix >> (i * 8));

    br_hmac_drbg_init(&g_drbg, &br_sha256_vtable, seed, sizeof seed);
    g_drbg_ready = true;
}

/* ----------------------------------------------------------------------------
 * 2. TLS engine — one shared client context plus its 16 KiB record buffers.
 *    BearSSL ships br_ssl_client_init_full(), a turnkey profile that
 *    enables every recommended cipher suite (ECDHE-RSA + ECDHE-ECDSA
 *    with AES-GCM / AES-CBC-SHA{256,384} / ChaCha20-Poly1305) and
 *    plumbs the X.509 minimal validator against a caller-supplied root
 *    trust anchor list.  No malloc, ~24 KiB of static state.
 * ---------------------------------------------------------------------------- */
static br_ssl_client_context     g_ssl;
static br_x509_minimal_context   g_xc;
static u8                        g_iobuf[BR_SSL_BUFSIZE_BIDI];

/* Trust anchors live in kernel/tls_roots.c (one entry today as a sanity
 * check; the full Mozilla bundle is generated by tools/build_roots.py
 * once we land the network stack — see network roadmap in README). */
extern const br_x509_trust_anchor TLS_ROOTS[];
extern const i32                  TLS_ROOTS_NUM;

/* ----------------------------------------------------------------------------
 * 3. Public API
 * ---------------------------------------------------------------------------- */
const char *tls_version(void)
{
    /* Tag matches the vendored upstream tarball (vendor/bearssl/README.txt). */
    return "BearSSL 0.6 (vendored)";
}

tls_result_t tls_init(void)
{
    if (!g_drbg_ready) tls_seed_drbg();

    if (!net_init() || !net_present()) {
        return TLS_ERR_NO_NETWORK;
    }

    /* br_ssl_client_init_full installs every recommended algorithm and
     * cipher suite into the engine; we override the RNG with our DRBG
     * so the entire stack draws from FalconOS's entropy. */
    br_ssl_client_init_full(&g_ssl, &g_xc, TLS_ROOTS, (size_t)TLS_ROOTS_NUM);
    br_ssl_engine_set_buffer(&g_ssl.eng, g_iobuf, sizeof g_iobuf, 1);
    br_ssl_engine_inject_entropy(&g_ssl.eng, g_iobuf, 32);

    return TLS_OK;
}

/* ----------------------------------------------------------------------------
 * 4. BearSSL system-seeder hook.
 *
 *    BearSSL's ssl_engine.c calls br_prng_seeder_system() when the engine
 *    is asked to auto-seed.  The default implementation lives in
 *    vendor/bearssl/src/rand/sysrng.c, which we exclude (it includes
 *    <fcntl.h>/<unistd.h>/wincrypt).  We re-supply a kernel-side stub
 *    that returns "no system seeder available" — callers must use
 *    br_ssl_engine_inject_entropy() with our HMAC_DRBG output instead,
 *    which we already do in tls_init().                                */
typedef int (*br_prng_seeder_fn)(const br_prng_class **ctx);
static int kernel_seeder(const br_prng_class **ctx)
{
    (void)ctx;
    return 0;
}
br_prng_seeder_fn br_prng_seeder_system(const char **name)
{
    if (name) *name = "falconos-hmac-drbg";
    return kernel_seeder;
}

tls_result_t tls_https_get(const char *url, char *out, u32 out_cap)
{
    if (!url || !out || out_cap < 2) return TLS_ERR_BUFFER_FULL;
    out[0] = 0;

    /* Parse "https://host[:port]/path".  Anything else is rejected — we
     * don't speak http://, ftp://, etc.  Port defaults to 443. */
    const char *p = url;
    if (p[0] != 'h' || p[1] != 't' || p[2] != 't' || p[3] != 'p' ||
        p[4] != 's' || p[5] != ':' || p[6] != '/' || p[7] != '/')
        return TLS_ERR_HTTP;
    p += 8;

    char host[64];
    i32 hi = 0;
    while (*p && *p != ':' && *p != '/' && hi < (i32)sizeof host - 1)
        host[hi++] = *p++;
    host[hi] = 0;

    /* TODO(v1.3-tls): once bareTCP and the DNS resolver land, this
     * sequence will execute end-to-end:
     *
     *   1.  dns_resolve(host, &ipv4);
     *   2.  tcp_connect(&sock, ipv4, port);
     *   3.  br_ssl_client_reset(&g_ssl, host, 0);
     *   4.  loop:
     *         st = br_ssl_engine_current_state(&g_ssl.eng);
     *         if (st & BR_SSL_SENDREC) tcp_write(...)
     *         if (st & BR_SSL_RECVREC) tcp_read(...)
     *         if (st & BR_SSL_SENDAPP) write HTTP GET
     *         if (st & BR_SSL_RECVAPP) append into out[]
     *         if (st & BR_SSL_CLOSED) break;
     *   5.  return TLS_OK if 200 OK, else TLS_ERR_HTTP.
     *
     * Today we exercise the BearSSL API far enough to force the linker
     * to keep the archive resident, then report UNCONFIGURED so callers
     * can detect the missing transport layer cleanly. */
    if (!g_drbg_ready) tls_seed_drbg();
    br_ssl_client_init_full(&g_ssl, &g_xc, TLS_ROOTS, (size_t)TLS_ROOTS_NUM);
    br_ssl_engine_set_buffer(&g_ssl.eng, g_iobuf, sizeof g_iobuf, 1);
    br_ssl_client_reset(&g_ssl, host, 0);

    return TLS_ERR_UNCONFIGURED;
}
