#!/usr/bin/env python3
"""
build_prg.py — FalconOS PRG package scaffolder.

A FalconOS package = one row in kernel/prg.c CATALOG[] + (optionally) a
cover screenshot under docs/store/<name>.png + a manifest under
packages/<name>/package.toml that future tooling can ingest.

This script generates all three from a single command line so that
adding a new package is reproducible (no copy/paste). It does NOT
modify kernel/prg.c automatically — instead it prints the C row to add,
so a human can review and paste it in.

Usage:
  python3 tools/build_prg.py <name> --version <ver> --summary "..." \
                                   --category <cat> --depends <pkg> \
                                   --size-kb <int> [--builtin]
                                   [--screenshot path-or-color]

If --screenshot is omitted, a 480x270 placeholder PNG is written using
only the Python standard library (raw 8-bit RGB chunked into a PNG with
manually computed CRCs — no Pillow required, so this works on a
freshly-bootstrapped CI runner).
"""
from __future__ import annotations

import argparse
import os
import struct
import zlib
from pathlib import Path
from typing import Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGES  = REPO_ROOT / "packages"
SHOTS     = REPO_ROOT / "docs" / "store"

CATEGORIES = {
    "core", "drivers", "themes", "apps", "games", "compat",
    "libraries", "fonts", "languages", "icons", "tools",
    "security", "system", "network",
}


def _hex(s: str) -> Tuple[int, int, int]:
    """Parse '#rrggbb' or 'rrggbb' or a named CSS-ish color into RGB."""
    s = s.strip().lstrip("#")
    if len(s) == 6:
        return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
    presets = {
        "blue":   (48, 112, 255),
        "purple": (164, 94, 229),
        "green":  (22, 181, 168),
        "pink":   (232, 93, 156),
        "graphite": (110, 120, 132),
        "cyan":   (0, 160, 229),
        "rose":   (215, 142, 132),
    }
    return presets.get(s.lower(), (48, 112, 255))


def _png(path: Path, w: int, h: int, rgb: Tuple[int, int, int]) -> None:
    """Write a flat-coloured PNG without Pillow (stdlib only)."""
    sig = b"\x89PNG\r\n\x1a\n"

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    raw = b""
    row = b"\x00" + bytes(rgb) * w  # filter byte + RGB per pixel
    for _ in range(h):
        raw += row
    idat = zlib.compress(raw, 9)
    blob = sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(blob)


def _toml(path: Path, args) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        f"# FalconOS package manifest — generated by tools/build_prg.py\n"
        f"# Do not edit manually; re-run the scaffolder if values change.\n\n"
        f"[package]\n"
        f"name      = \"{args.name}\"\n"
        f"version   = \"{args.version}\"\n"
        f"summary   = \"{args.summary}\"\n"
        f"category  = \"{args.category}\"\n"
        f"depends   = \"{args.depends or ''}\"\n"
        f"size_kb   = {args.size_kb}\n"
        f"builtin   = {str(bool(args.builtin)).lower()}\n\n"
        f"[install]\n"
        f"# These run only when the user clicks Install in the Store app.\n"
        f"# Bare-metal FalconOS has no shell pre/post hooks yet; values\n"
        f"# below are recorded for the future package runner.\n"
        f"pre  = []\n"
        f"post = []\n\n"
        f"[ui]\n"
        f"icon       = \"icons/{args.name}.png\"\n"
        f"screenshot = \"docs/store/{args.name}.png\"\n"
    )
    path.write_text(body, encoding="utf-8")


def _c_row(args) -> str:
    return (
        f'    {{ "{args.name}",'
        f' "{args.version}", '
        f'"{args.summary}", '
        f'"{args.category}", '
        f'"{args.depends or ""}", '
        f'{args.size_kb}, '
        f'{"true " if args.builtin else "false"} }},'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name")
    parser.add_argument("--version",  default="0.1.0")
    parser.add_argument("--summary",  default="")
    parser.add_argument("--category", default="apps", choices=sorted(CATEGORIES))
    parser.add_argument("--depends",  default="")
    parser.add_argument("--size-kb",  type=int, default=4)
    parser.add_argument("--builtin",  action="store_true")
    parser.add_argument(
        "--screenshot",
        default="cyan",
        help="Either a path to a PNG, or a color name (blue/cyan/...).",
    )
    args = parser.parse_args()

    if not args.summary:
        args.summary = f"{args.name} — FalconOS package"

    pkg_dir = PACKAGES / args.name
    _toml(pkg_dir / "package.toml", args)

    shot = SHOTS / f"{args.name}.png"
    if os.path.isfile(args.screenshot):
        # copy provided image
        from shutil import copyfile
        SHOTS.mkdir(parents=True, exist_ok=True)
        copyfile(args.screenshot, shot)
    else:
        _png(shot, 480, 270, _hex(args.screenshot))

    print(f"[OK] {pkg_dir.relative_to(REPO_ROOT)}/package.toml")
    print(f"[OK] {shot.relative_to(REPO_ROOT)}")
    print()
    print("Now add this row to kernel/prg.c CATALOG[]:")
    print(_c_row(args))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
