#!/usr/bin/env python3
"""
FalconOS — bitmap-font generator (antialiased 8×16 + 1-bit 16×32).

Renders printable ASCII (0x20-0x7E) from DejaVu Sans Mono and emits
`kernel/font_data.c` with two tables:

  - FONT8X16  [95][128]  — *grayscale* 8 px wide × 16 px tall, one byte
                            per pixel (0 = transparent, 255 = solid).
                            gfx_text() alpha-blends these onto the back
                            buffer giving smooth antialiased text at the
                            same metrics as the old 1-bit font.
  - FONT16X32 [95][64]   — sharp 1-bit bitmap, 16 px wide × 32 px tall;
                            two bytes per row, MSB = leftmost pixel.
                            Used by gfx_text_lg() for headings.

Used only at *build time* — the kernel itself never depends on this file.
"""
from __future__ import annotations

import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]

FIRST, LAST = 0x20, 0x7E      # printable ASCII


def find_font() -> str:
    for p in FONT_PATHS:
        if pathlib.Path(p).exists():
            return p
    sys.exit("DejaVu Sans Mono not found — install fonts-dejavu-core")


def render_grayscale(font_path: str, font_size_px: int, ch: str,
                     w: int, h: int,
                     nudge_x: int = 0, nudge_y: int = 0) -> list[int]:
    """Render `ch` at 4× supersampling and downsample with Lanczos for
    crisp antialiased edges, return w*h alpha bytes (row-major)."""
    sup = 4
    big_font = ImageFont.truetype(font_path, font_size_px * sup)
    img = Image.new("L", (w * sup, h * sup), 0)
    draw = ImageDraw.Draw(img)
    draw.text((nudge_x * sup, nudge_y * sup),
              ch, fill=255, font=big_font)
    # Downsample to the cell size; LANCZOS preserves curves.
    img = img.resize((w, h), Image.LANCZOS)
    pixels: list[int] = []
    for y in range(h):
        for x in range(w):
            pixels.append(img.getpixel((x, y)))
    return pixels


def render_bilevel(font: ImageFont.FreeTypeFont, ch: str,
                   w: int, h: int, threshold: int,
                   nudge_x: int = 0, nudge_y: int = 0) -> list[int]:
    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((nudge_x, nudge_y), ch, fill=255, font=font)
    rows: list[int] = []
    for y in range(h):
        bits = 0
        for x in range(w):
            if img.getpixel((x, y)) >= threshold:
                bits |= (1 << (w - 1 - x))
        rows.append(bits)
    return rows


def main() -> None:
    font_path = find_font()
    f16 = ImageFont.truetype(font_path, 28)   # for the bilevel headline font
    out = ROOT / "kernel" / "font_data.c"

    lines = [
        "/* AUTO-GENERATED by tools/genfont.py — do not edit. */",
        '#include "falcon.h"',
        "",
        "/* 8×16 antialiased font — row-major, one byte (alpha) per pixel.",
        " * Index: FONT8X16[glyph][y * 8 + x].                              */",
        "const u8 FONT8X16[95][128] = {",
    ]
    for code in range(FIRST, LAST + 1):
        # 14 px fits the 8×16 cell with descender room; supersampled 4× for AA.
        px = render_grayscale(font_path, 14, chr(code),
                              8, 16, nudge_x=-1, nudge_y=0)
        body = ", ".join(f"0x{b:02X}" for b in px)
        glyph = chr(code) if 0x20 < code < 0x7F else " "
        lines.append(f"    {{ {body} }}, /* 0x{code:02X} '{glyph}' */")
    lines.append("};")
    lines.append("")

    lines.extend([
        "/* 16×32 1-bit headline font — two bytes per row, MSB = leftmost. */",
        "const u8 FONT16X32[95][64] = {",
    ])
    for code in range(FIRST, LAST + 1):
        rows = render_bilevel(f16, chr(code), 16, 32, 96,
                              nudge_x=-2, nudge_y=-2)
        flat: list[int] = []
        for r in rows:
            flat.append((r >> 8) & 0xFF)
            flat.append(r & 0xFF)
        body = ", ".join(f"0x{b:02X}" for b in flat)
        glyph = chr(code) if 0x20 < code < 0x7F else " "
        lines.append(f"    {{ {body} }}, /* 0x{code:02X} '{glyph}' */")
    lines.append("};")
    lines.append("")

    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} "
          f"({LAST - FIRST + 1} glyphs × 2 styles)")


if __name__ == "__main__":
    main()
