#!/usr/bin/env python3
"""
FalconOS — 8 × 16 font generator.

Renders printable ASCII (0x20-0x7E) from DejaVu Sans Mono into a packed
8 × 16 bitmap and emits `kernel/font_data.c` (a 95-row × 16-byte array).

Used only at *build time* — the kernel itself never depends on this file.
"""
from __future__ import annotations

import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]

FIRST, LAST = 0x20, 0x7E      # printable ASCII
W, H        = 8, 16
PX_SIZE     = 14              # font size that fits 8×16 nicely
THRESHOLD   = 110             # alpha cut-off


def find_font() -> str:
    for p in FONT_PATHS:
        if pathlib.Path(p).exists():
            return p
    sys.exit("DejaVu Sans Mono not found — install fonts-dejavu-core")


def render_char(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    # nudge baseline so glyphs sit centred in the 8×16 cell
    draw.text((-1, 0), ch, fill=255, font=font)
    rows: list[int] = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) >= THRESHOLD:
                bits |= 0x80 >> x
        rows.append(bits)
    return rows


def main() -> None:
    font = ImageFont.truetype(find_font(), PX_SIZE)
    out = ROOT / "kernel" / "font_data.c"

    lines = [
        "/* AUTO-GENERATED by tools/genfont.py — do not edit. */",
        '#include "falcon.h"',
        "",
        "const u8 FONT8X16[95][16] = {",
    ]
    for code in range(FIRST, LAST + 1):
        rows = render_char(font, chr(code))
        body = ", ".join(f"0x{b:02X}" for b in rows)
        glyph = chr(code) if 0x20 < code < 0x7F else " "
        lines.append(f"    {{ {body} }}, /* 0x{code:02X} '{glyph}' */")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} ({LAST - FIRST + 1} glyphs)")


if __name__ == "__main__":
    main()
